import type { Plugin } from 'vite';

/**
 * Dependency-free PWA build plugin (stand-in for `vite-plugin-pwa`, which we
 * can't vendor): emits `manifest.webmanifest` plus a `sw.js` that precaches
 * the build's assets. The service worker is cache-first for same-origin
 * static files and network-first for navigations, and activates a new
 * version only when the page posts `SKIP_WAITING` (see `src/shared/lib/pwa.ts`
 * for the update-prompt side).
 */
export function auraPWA(version: string): Plugin {
  return {
    name: 'aura-pwa',
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .filter((file) => file !== 'sw.js')
        .map((file) => `/${file}`);

      this.emitFile({
        type: 'asset',
        fileName: 'manifest.webmanifest',
        source: JSON.stringify(manifest, null, 2),
      });
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(version, assets),
      });
    },
  };
}

const manifest = {
  name: 'Aura',
  short_name: 'Aura',
  description: 'Aura web app',
  display: 'standalone',
  theme_color: '#0c0a09',
  background_color: '#0c0a09',
  start_url: '/',
  icons: [
    {
      src: '/global/aura-192x192.png',
      sizes: '192x192',
      type: 'image/png',
    },
    {
      src: '/global/aura-256x256.png',
      sizes: '256x256',
      type: 'image/png',
      purpose: 'any maskable',
    },
    {
      src: '/global/aura-512x512.png',
      sizes: '512x512',
      type: 'image/png',
    },
  ],
};

// Files from public/ aren't in the rollup bundle — precache them explicitly.
const PUBLIC_ASSETS = [
  '/',
  '/global/logo.png',
  '/global/aura-192x192.png',
  '/global/aura-256x256.png',
  '/global/aura-512x512.png',
];

const swSource = (version: string, assets: string[]) => `// generated by aura-pwa (${version})
const CACHE = "aura-${version}"
const ASSETS = ${JSON.stringify([...PUBLIC_ASSETS, ...assets])}

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)))
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  )
})

// The page decides when a waiting version activates (update prompt).
self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting()
})

self.addEventListener("fetch", (event) => {
  const request = event.request
  if (request.method !== "GET") return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  // Never intercept API proxies — only precached static files are served
  // from cache; everything else falls through to the network untouched.
  if (request.mode === "navigate") {
    event.respondWith(fetch(request).catch(() => caches.match("/")))
    return
  }
  event.respondWith(
    caches.match(request).then((hit) => hit ?? fetch(request)),
  )
})
`;
