import { createHash } from 'node:crypto';
import type { Plugin } from 'vite';

/**
 * Dependency-free PWA build plugin (stand-in for `vite-plugin-pwa`, which we
 * can't vendor): emits `manifest.webmanifest` plus a `sw.js` that precaches
 * the build's assets. The service worker is cache-first for those precached
 * URLs only. Navigations and API requests are not intercepted. A new version
 * activates only when the page posts `SKIP_WAITING` (see `src/shared/lib/pwa.ts`).
 */
export function auraPWA(version: string): Plugin {
  return {
    name: 'aura-pwa',
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = [
        ...PUBLIC_ASSETS,
        ...Object.keys(bundle)
          .filter((file) => file !== 'sw.js' && !file.endsWith('.html'))
          .map((file) => `/core/${file}`)
          .sort(),
      ];

      this.emitFile({
        type: 'asset',
        fileName: 'manifest.webmanifest',
        source: JSON.stringify(manifest, null, 2),
      });
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(version, assets, precacheId(assets)),
      });
    },
  };
}

const manifest = {
  name: 'Aura',
  short_name: 'Aura',
  description: 'Aura web app',
  display: 'standalone',
  theme_color: '#0c0a09',
  background_color: '#0c0a09',
  start_url: '/core/',
  scope: '/core/',
  icons: [
    {
      src: '/core/global/logo.png',
      sizes: '1024x1024',
      type: 'image/png',
      purpose: 'any',
    },
  ],
};

// Files from public/ aren't in the rollup bundle — precache them explicitly.
// Only files that exist. Missing icons 404 in preview and, on the landing
// host, come back as index.html with status 200, which poisons the cache.
const PUBLIC_ASSETS = ['/core/global/logo.png'];

function precacheId(assets: string[]): string {
  return createHash('sha256')
    .update(assets.join('\0'))
    .digest('hex')
    .slice(0, 12);
}

const swSource = (
  version: string,
  assets: string[],
  cacheId: string,
) => `// generated by aura-pwa (${version})
const CACHE = ${JSON.stringify(`aura-${cacheId}`)}
const ASSETS = ${JSON.stringify(assets)}
const ASSET_SET = new Set(ASSETS)

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)))
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  )
})

// The page decides when a waiting version activates (update prompt).
self.addEventListener("message", (event) => {
  const data = event.data
  if (data === "SKIP_WAITING" || (data && data.type === "SKIP_WAITING")) {
    event.waitUntil(self.skipWaiting())
    return
  }
  if (data && data.type === "GET_VERSION" && event.ports[0]) {
    event.ports[0].postMessage({ cache: CACHE })
  }
})

self.addEventListener("fetch", (event) => {
  const request = event.request
  if (request.method !== "GET") return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  // Precached static files only. Navigations and API GETs hit the network.
  if (!ASSET_SET.has(url.pathname)) return
  event.respondWith(
    caches.match(request).then((hit) => hit ?? fetch(request)),
  )
})
`;
